# Generated by Django 6.0.3 on 2026-04-02 12:24

import datetime
import django.db.models.deletion
import lab_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('others', 'Others')], max_length=20)),
                ('recorded_date', models.DateField(default=datetime.date.today)),
                ('pdf_result', models.FileField(upload_to=lab_core.models.lab_result_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date', '-id'],
            },
        ),
    ]
