# Generated by Django 6.0.3 on 2026-04-02 14:33

import lab_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0002_labresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=lab_core.models.blog_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
