# Generated by Django 6.0.3 on 2026-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0004_blogpost_description_blogpost_hearts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('link_label', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
