# Generated by Django 6.0.3 on 2026-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0005_labannouncement_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Under Processing'), ('REVIEW', 'Under Review'), ('COMPLETED', 'Ready for Download')], default='PENDING', max_length=15),
        ),
    ]
