# Generated by Django 6.0.3 on 2026-04-04 09:00

import datetime
import django.db.models.deletion
import django.utils.timezone
import lab_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0006_labresult_expected_delivery_labresult_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AlterModelOptions(
            name='labannouncement',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Lab announcement', 'verbose_name_plural': 'Lab announcements'},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-created_at', '-recorded_date', '-id'], 'verbose_name': 'Test result', 'verbose_name_plural': 'Test results'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient profile', 'verbose_name_plural': 'Patient profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='labresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='hearted_posts', to=settings.AUTH_USER_MODEL, verbose_name='Hearts'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lab_core.models.blog_image_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Posted by'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='link_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Link label'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='labannouncement',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='category',
            field=models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('others', 'Others')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected delivery'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish status'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='pdf_result',
            field=models.FileField(upload_to=lab_core.models.lab_result_upload_path, verbose_name='PDF result'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='recorded_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Under Processing'), ('REVIEW', 'Under Review'), ('COMPLETED', 'Ready for Download')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(max_length=255, verbose_name='Test name'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone number'),
        ),
    ]
