# Generated by Django 6.0.3 on 2026-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0007_labresult_created_at_and_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
