# Generated by Django 6.0.3 on 2026-06-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_core', '0008_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
